SCALING_OUT_CPU_THRESHOLD     = 0.5
SCALING_IN_CPU_THRESHOLD      = 0.2

SCALING_OUT_MEMORY_THRESHOLD  = 0.8
SCALING_IN_MEMORY_THRESHOLD   = 0.2

PING_PONG_EFFECT_THRESHOLD    = 0.1

QUERY_INTERVAL                = 30 # seconds